apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 2  # Number of pod replicas
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-container
        image: memcached:latest  # Using Memcached image
        ports:
        - containerPort: 80  # Change if your app runs on a different port
      imagePullSecrets:
      - name: my-registry-secret  # If pulling from a private registry
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80  # External port
      targetPort: 80  # Container port
  type: LoadBalancer  # Change to NodePort or ClusterIP as needed
